### ISSUE TITLE
Getting Lines below Title in Splash Screen

### ISSUE THREAD

**Issue by pratikbutani** [flutter-clutter/flutter-animated-splash-screen#1]
Why I am getting two lines below the "Raindrop Software"? I have implemented same code as it is.

Any Solution?

![device-2020-09-24-143329](https://user-images.githubusercontent.com/3306366/94124727-fcd89280-fe72-11ea-84eb-008730e73293.png)

**Comment by flutter-clutter** [comment]
@pratikbutani Oh I'm sorry, I have to admit I haven't noticed this issue. Otherwise I would have responded earlier.
Have you cloned this repository? This issue usually appears when the default TextStyle is set. This TextStyle is typically overriden when you use a Scaffold (inside a MaterialApp). So two possible solutions:
1.) Wrap you widget inside a Scaffold widget
2.) Override the TextStyle yourself using the "style" property of the text. I hope that helps and sorry for the late response.

**Comment by pratikbutani** [comment]
Solved by using the first option, added a **Scaffold** widget with **background** transparent.

    Scaffold( 
            backgroundColor: Colors.transparent,
            body: ...
            ...
    );

Thank you 👍
